### ISSUE TITLE
代码Review，提点小建议哈

### ISSUE THREAD

**Issue by QingFlye** [waterVenice7/vquery#2]
# one.js
## 事件相关
1.  **L48、L61**  ，委托都已经成了共识了，为什么要强制取消冒泡呢？
2. **L52**  不要再用`return false`来取消默认行为了，对于IE应当使用`ev.returnValue = false`
3. **L60**  我第一次发现`addEventListener`需要兼容全局事件，实际上连'attachEvent'都不需要做这个处理的，`ev = ev || event`这是个传了很多年的谣言。
4. **L69**  这个函数可以直接去掉，使用`myAddEvent`绑定的事件永远不可能使用这个函数来解绑。
5. **L50、L62** 执行fn不传递事件对象，如何获取鼠标事件的鼠标位置，获取键盘事件的按键？
## getByClass
1. **L84** 分割类使用\b不靠谱的，可以去看看CSS转义字符，其实还有`I\ am\ a\ real\ class\ name`这样的选择器。
2. **L87** 这句话在IE67不可能执行的，因为IE67下`getElementsByTagName`会返回非元素节点，而非元素节点不存在className这个属性，所以这相当于`undefined.search`
## getStyle

这个函数看起来没什么错误，但是显然没有处理相对单位的问题，而且包括width/height在内的很多属性用这个方法并不能获取到真实的值。
## getIndex
1. **L107**  如果元素没有父亲节点会怎么样？
2. 使用sibling来迭代子元素会更快
3. 这样迭代会迭代出非元素节点，确认你不要处理掉这些节点么？
## startMove
1. **L120-L127** 直接写成var fre = arguments[3] || 30就可以了，另外更优雅的写法是把fre写在参数里面，然后写fre = fre || 30，这样代码在压缩后会小很多，可以了解一下代码体积优化。
2. **L133** 要不要考虑一下如果用户传递了非法值怎么办
3. 从上到下的计算结果都可能是NaN，给CSS的值设置为NaN会丢出异常
4. 按你的算法，如果把元素的大小从30% 改成500px会出现什么情况
5. **L151** 如果值是NaN这个判断一定会为true，怎么办？

作者seven在qq空间分享了这个代码库的github链接，好奇心点了进去，本着学习的态度提了上面的意见，希望一起探讨学习交流，如果有不对，欢迎指正哈，希望一起学习进步，积极交流，共同成长。O(∩_∩)O

**Comment by seven654321** [comment]
抱歉这么久了才来回复这个消息，感谢QingFlye同学的建议，

- 本人因为当时资源的限制还有自身姿势的不完善，在大约两年前尝试写了这个轮子，后来逐渐改善修正，但是最后还是发现精力有限可能无法继续维持,后续会按照标准文档的格式写下api的使用方法以及设计思路，对于同学提出的逻辑上的漏洞也会考虑一一调整，希望对造轮子感兴趣的人有一些帮助
- 对于自身性格上的缺点，例如敏感、多疑，本人在实习过程中也已经认识到，在后续的生活中会尝试改变。
- 造轮子还是我的爱好，哈哈，这个是不会停的
